apiVersion: apps/v1
kind: Deployment
metadata:
  name: testname
  labels:
    app: testname
spec:
  replicas: 1
  template:
    metadata:
      name: testname
      labels:
        app: testname
    spec:
      containers:
        - name: testname
          image: busybox
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: testname
